/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSanctumRouteImport } from './routes/_authenticated/sanctum'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedGuideRouteImport } from './routes/_authenticated/guide'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCommonsIndexRouteImport } from './routes/_authenticated/commons.index'
import { Route as AuthenticatedGuideIdRouteImport } from './routes/_authenticated/guide.$id'
import { Route as AuthenticatedCommonsNewRouteImport } from './routes/_authenticated/commons.new'
import { Route as AuthenticatedCommonsIdRouteImport } from './routes/_authenticated/commons.$id'
import { Route as AuthenticatedAdminAcceptTokenRouteImport } from './routes/_authenticated/admin.accept.$token'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSanctumRoute = AuthenticatedSanctumRouteImport.update({
  id: '/sanctum',
  path: '/sanctum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuideRoute = AuthenticatedGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommonsIndexRoute =
  AuthenticatedCommonsIndexRouteImport.update({
    id: '/commons/',
    path: '/commons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuideIdRoute = AuthenticatedGuideIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedGuideRoute,
} as any)
const AuthenticatedCommonsNewRoute = AuthenticatedCommonsNewRouteImport.update({
  id: '/commons/new',
  path: '/commons/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommonsIdRoute = AuthenticatedCommonsIdRouteImport.update({
  id: '/commons/$id',
  path: '/commons/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAcceptTokenRoute =
  AuthenticatedAdminAcceptTokenRouteImport.update({
    id: '/accept/$token',
    path: '/accept/$token',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/guide': typeof AuthenticatedGuideRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/sanctum': typeof AuthenticatedSanctumRoute
  '/commons/$id': typeof AuthenticatedCommonsIdRoute
  '/commons/new': typeof AuthenticatedCommonsNewRoute
  '/guide/$id': typeof AuthenticatedGuideIdRoute
  '/commons/': typeof AuthenticatedCommonsIndexRoute
  '/admin/accept/$token': typeof AuthenticatedAdminAcceptTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/guide': typeof AuthenticatedGuideRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/sanctum': typeof AuthenticatedSanctumRoute
  '/commons/$id': typeof AuthenticatedCommonsIdRoute
  '/commons/new': typeof AuthenticatedCommonsNewRoute
  '/guide/$id': typeof AuthenticatedGuideIdRoute
  '/commons': typeof AuthenticatedCommonsIndexRoute
  '/admin/accept/$token': typeof AuthenticatedAdminAcceptTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/guide': typeof AuthenticatedGuideRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/sanctum': typeof AuthenticatedSanctumRoute
  '/_authenticated/commons/$id': typeof AuthenticatedCommonsIdRoute
  '/_authenticated/commons/new': typeof AuthenticatedCommonsNewRoute
  '/_authenticated/guide/$id': typeof AuthenticatedGuideIdRoute
  '/_authenticated/commons/': typeof AuthenticatedCommonsIndexRoute
  '/_authenticated/admin/accept/$token': typeof AuthenticatedAdminAcceptTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/guide'
    | '/onboarding'
    | '/sanctum'
    | '/commons/$id'
    | '/commons/new'
    | '/guide/$id'
    | '/commons/'
    | '/admin/accept/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/guide'
    | '/onboarding'
    | '/sanctum'
    | '/commons/$id'
    | '/commons/new'
    | '/guide/$id'
    | '/commons'
    | '/admin/accept/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/guide'
    | '/_authenticated/onboarding'
    | '/_authenticated/sanctum'
    | '/_authenticated/commons/$id'
    | '/_authenticated/commons/new'
    | '/_authenticated/guide/$id'
    | '/_authenticated/commons/'
    | '/_authenticated/admin/accept/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sanctum': {
      id: '/_authenticated/sanctum'
      path: '/sanctum'
      fullPath: '/sanctum'
      preLoaderRoute: typeof AuthenticatedSanctumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guide': {
      id: '/_authenticated/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthenticatedGuideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commons/': {
      id: '/_authenticated/commons/'
      path: '/commons'
      fullPath: '/commons/'
      preLoaderRoute: typeof AuthenticatedCommonsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guide/$id': {
      id: '/_authenticated/guide/$id'
      path: '/$id'
      fullPath: '/guide/$id'
      preLoaderRoute: typeof AuthenticatedGuideIdRouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/commons/new': {
      id: '/_authenticated/commons/new'
      path: '/commons/new'
      fullPath: '/commons/new'
      preLoaderRoute: typeof AuthenticatedCommonsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commons/$id': {
      id: '/_authenticated/commons/$id'
      path: '/commons/$id'
      fullPath: '/commons/$id'
      preLoaderRoute: typeof AuthenticatedCommonsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/accept/$token': {
      id: '/_authenticated/admin/accept/$token'
      path: '/accept/$token'
      fullPath: '/admin/accept/$token'
      preLoaderRoute: typeof AuthenticatedAdminAcceptTokenRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAcceptTokenRoute: typeof AuthenticatedAdminAcceptTokenRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAcceptTokenRoute: AuthenticatedAdminAcceptTokenRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedGuideRouteChildren {
  AuthenticatedGuideIdRoute: typeof AuthenticatedGuideIdRoute
}

const AuthenticatedGuideRouteChildren: AuthenticatedGuideRouteChildren = {
  AuthenticatedGuideIdRoute: AuthenticatedGuideIdRoute,
}

const AuthenticatedGuideRouteWithChildren =
  AuthenticatedGuideRoute._addFileChildren(AuthenticatedGuideRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedGuideRoute: typeof AuthenticatedGuideRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSanctumRoute: typeof AuthenticatedSanctumRoute
  AuthenticatedCommonsIdRoute: typeof AuthenticatedCommonsIdRoute
  AuthenticatedCommonsNewRoute: typeof AuthenticatedCommonsNewRoute
  AuthenticatedCommonsIndexRoute: typeof AuthenticatedCommonsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedGuideRoute: AuthenticatedGuideRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSanctumRoute: AuthenticatedSanctumRoute,
  AuthenticatedCommonsIdRoute: AuthenticatedCommonsIdRoute,
  AuthenticatedCommonsNewRoute: AuthenticatedCommonsNewRoute,
  AuthenticatedCommonsIndexRoute: AuthenticatedCommonsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
